name: ${project.build.finalName}
main: ${mainClass}
version: ${project.version}
author: SupaHam
description: TenJava plugin
commands:
    supaarrows:
        description: SupaArrows main command
        aliases: [sa, supaa, sarrows]
